// This file is generated by npm run build:icons

export type IconName =
	| "add-circle"
	| "add"
	| "badge-plus"
	| "check"
	| "chevron-down"
	| "chevron-right"
	| "chevron-up"
	| "cross-2"
	| "cross"
	| "delete"
	| "external-link"
	| "pencil"
	| "plus"
	| "search"
